### ISSUE TITLE
Pivot from Unity to Phaser

### ISSUE THREAD

**Issue by yogiduzit** [yogiduzit/Ocean-Defenders#71]
After months of thorough research, it has been deemed that games made using phaser have superior quality compared to the games made using Unity.

**Comment by yogiduzit** [comment]
FYI, @herbertmaa @RoyArka @Gjhinger @BWhite1395

**Comment by RoyArka** [comment]
This guy man lol

**Comment by herbertmaa** [comment]
Agreed. Please proceed with port over, make a pull-request and @BWhite1395 will take a look.

**Comment by RoyArka** [comment]
What . . . im closing this.

**Comment by yogiduzit** [comment]
@herbertmaa Request to kick @RoyArka from this project
